- name: dist-upgrade Proxmox host
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  
  tasks:
    - name: update APT cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: perform full dist-upgrade
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
