- name: Backup all Proxmox VMs to DIR
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  vars:
    backup_dir: "/mnt/backup"  # You can override this

  tasks:
    - name: Get list of VM IDs
      shell: qm list | awk 'NR>1 {print $1}'
      register: vm_list_raw

    - name: Set VM ID list
      set_fact:
        vm_ids: "{{ vm_list_raw.stdout_lines }}"

    - name: Backup each VM to custom directory
      shell: vzdump {{ item }} --mode snapshot --compress zstd --dumpdir {{ backup_dir }}
      loop: "{{ vm_ids }}"
      when: vm_ids is defined
