- name: Run existing Proxmox backup job by ID
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  vars:
    backup_job_ids: [1, 3]

  tasks:
    - name: Start backup job {{ item }}
      shell: systemctl start pve-daily-backup@{{ item }}.service
      loop: "{{ backup_job_ids }}"
