- name: Run existing Proxmox backup job by ID
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  vars:
    backup_job_ids:
      - backup-9f2a20d2-67ca
      - backup-b0f2737d-487f

  tasks:
    - name: Start backup job {{ item }}
      shell: systemctl start pve-manager-backup@{{ item }}.service
      loop: "{{ backup_job_ids }}"
