- name: Backup all Proxmox VMs and LXC to PBS
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  vars:
    pbs_storage: "pbs-backup"
    backup_mode: "snapshot"

  tasks:
    - name: Get list of KVM VM IDs
      shell: qm list | awk 'NR>1 {print $1}'
      register: vm_list_raw

    - name: Get list of LXC container IDs
      shell: pct list | awk 'NR>1 {print $1}'
      register: lxc_list_raw

    - name: Combine VM and LXC IDs
      set_fact:
        all_ids: "{{ vm_list_raw.stdout_lines + lxc_list_raw.stdout_lines }}"

    - name: Backup each VM or LXC to PBS (no email notifications)
      shell: >
        vzdump {{ item }} 
        --mode {{ backup_mode }} 
        --storage {{ pbs_storage }} 
        --compress zstd 
        --mailnotification failure
      loop: "{{ all_ids }}"
      when: all_ids is defined
