# basic non-root backup for Proxmox hosts

- name: Run PBS basic file-level backup
  hosts: all
  gather_facts: no

  vars:
    pbs_server: "10.100.0.75"
    pbs_datastore: "hosts-backup"
    pbs_username: "root@pam!hosts-backup"
    pbs_secret: "{{ vault_pbs_secret }}"
    pbs_fingerprint: "11:22:33:44:55...."

  tasks:
    - name: Start basic backup
      ansible.builtin.command:
        argv:
          - proxmox-backup-client
          - backup
          - hosts.pxar:/etc/hosts
          - hostname.pxar:/etc/hostname
          - resolv.pxar:/etc/resolv.conf
          - network.pxar:/etc/network
          - apt-sources.pxar:/etc/apt/sources.list.d
      environment:
        PBS_REPOSITORY: "{{ pbs_username }}@{{ pbs_server }}:{{ pbs_datastore }}"
        PBS_PASSWORD: "{{ pbs_secret }}"
        PBS_FINGERPRINT: "{{ pbs_fingerprint }}"
      no_log: true
