- name: replication for VM or LXC
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  vars:
    vm_ids_to_replicate: [101, 202]  # Both VM (qm) and LXC (pct)
    target_node: "pve-200"
    job_suffix: "0"  # Arbitrary number to avoid collision

  tasks:
    - name: Set list of valid VM/CT IDs
      set_fact:
        existing_vm_ids: "{{ vm_check.results | selectattr('rc', 'equalto', 0) | map(attribute='item') | list }}"

    - name: Run replication immediately
      shell: >
        pvesr run --id {{ item }}-{{ job_suffix }} --verbose
      loop: "{{ existing_vm_ids }}"
