- name: Run replication for VM or LXC (only if task exists)
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  ignore_errors: yes

  vars:
    vm_ids_to_replicate: [101, 202]
    job_suffix: "0"  # Job number used in replication ID

  tasks:
    - name: Check if replication job exists
      shell: pvesr read {{ item }}-{{ job_suffix }}
      register: vm_check
      failed_when: false
      changed_when: false
      loop: "{{ vm_ids_to_replicate }}"
      loop_control:
        label: "{{ item }}"

    - name: Set list of VM/CT IDs with existing replication jobs
      set_fact:
        existing_vm_ids: "{{ vm_check.results | selectattr('rc', 'equalto', 0) | map(attribute='item') | list }}"

    - name: Run replication immediately for existing jobs
      shell: pvesr run --id {{ item }}-{{ job_suffix }} --verbose
      loop: "{{ existing_vm_ids }}"
