- name: Start VM or LXC on Proxmox based on vm_id
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  vars:
    vm_id: "000"

  tasks:
    - name: Check if VM exists
      command: qm status {{ vm_id }}
      register: qm_check
      ignore_errors: yes

    - name: Check if LXC container exists
      command: pct status {{ vm_id }}
      register: pct_check
      when: qm_check.rc != 0
      ignore_errors: yes

    - name: Fail if VM or LXC not found
      fail:
        msg: "VM or LXC with ID {{ vm_id }} not found on this node."
      when: qm_check.rc != 0 and (pct_check is not defined or pct_check.rc != 0)

    - name: Start VM
      command: qm start {{ vm_id }}
      when: qm_check.rc == 0

    - name: Start LXC container
      command: pct start {{ vm_id }}
      when: qm_check.rc != 0 and pct_check.rc == 0
