- name: start VM or LXC on Proxmox based on vm_id (if you are working in a cluster env let this script run on every node)
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  vars:
    vm_id: "000"

  tasks:
    - name: check if VM exists
      command: qm status {{ vm_id }}
      register: qm_check
      ignore_errors: yes

    - name: check if LXC container exists
      command: pct status {{ vm_id }}
      register: pct_check
      when: qm_check.rc != 0
      ignore_errors: yes

    - name: fail if VM or LXC not found
      fail:
        msg: "VM or LXC with ID {{ vm_id }} not found on this node."
      when: qm_check.rc != 0 and (pct_check is not defined or pct_check.rc != 0)

    - name: debug - VM found on this node
      debug:
        msg: "VM with ID {{ vm_id }} found on node {{ inventory_hostname }}, starting..."
      when: qm_check.rc == 0

    - name: debug - LXC found on this node
      debug:
        msg: "LXC container with ID {{ vm_id }} found on node {{ inventory_hostname }}, starting..."
      when: qm_check.rc != 0 and pct_check.rc == 0

    - name: start VM
      command: qm start {{ vm_id }}
      when: qm_check.rc == 0

    - name: start LXC container
      command: pct start {{ vm_id }}
      when: qm_check.rc != 0 and pct_check.rc == 0
