- name: Scan Nextcloud User dir for sync
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  vars:
    nextcloud_user: "admin"
    nextcloud_occ: "/var/www/nextcloud/occ"
    
  tasks:
    - name: Run Nextcloud files scan for specified user
      ansible.builtin.command: >
        sudo -u www-data php {{ nextcloud_occ }} files:scan {{ nextcloud_user }}
      register: scan_output

    - name: Show scan output
      ansible.builtin.debug:
        var: scan_output.stdout
