{
 "title": "truenas-monitor",
 "description": "A simple and clean TrueNAS Core/Scale grafana dashboard based on prometheus",
 "tags": [ "truenas" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "hostname", "query": { "query": "truenas_uptime_uptime" } }
  ]
 },
 "panels": [
  {
   "title": "Disk Temperature",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmon_temperature_celsius_raw_value{smart_id=\"194\", type=\"sat\"}\n  * on(disk) group_left(serial_number, device_model)\n    smartmon_device_info{type=\"sat\", instance=\"10.100.0.20:9100\"}",
     "legendFormat": "{{ device_model }}"
    }
   ]
  },
  {
   "title": "Interface Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "{__name__=~\"scale_truenas_net_ens.*_received\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{__name__=~\"scale_truenas_net_ens.*_sent\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "RAM Free",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "scale_truenas_system_ram_free", "legendFormat": "Usage" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - scale_truenas_system_cpu_idle",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ARC Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "scale_truenas_zfs_arc_size_arcsz",
     "legendFormat": "ARC"
    }
   ]
  },
  {
   "title": "Disk I/O time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (disk, op) (\n  label_replace(\n    label_replace(\n      {__name__=~\"scale_truenas_disk_await_.+_(reads|writes)\"},\n      \"disk\", \"$1\", \"__name__\", \"scale_truenas_disk_await_(.+)_(?:reads|writes)\"\n    ),\n    \"op\", \"$1\", \"__name__\", \"scale_truenas_disk_await_.+_(reads|writes)\"\n  )\n)",
     "legendFormat": "{{disk }} - {{ op }}"
    }
   ]
  },
  {
   "title": "Disk RW speed",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "(\n  avg by (disk, op) (\n    label_replace(\n      label_replace(\n        {__name__=~\"scale_truenas_disk_ops_.+_(reads|writes)\"},\n        \"disk\", \"$1\", \"__name__\", \"scale_truenas_disk_ops_(.+)_(?:reads|writes)\"\n      ),\n      \"op\", \"$1\", \"__name__\", \"scale_truenas_disk_ops_.+_(reads|writes)\"\n    )\n  )\n  *\n  avg by (disk, op) (\n    label_replace(\n      label_replace(\n        {__name__=~\"scale_truenas_disk_avgsz_.+_(reads|writes)\"},\n        \"disk\", \"$1\", \"__name__\", \"scale_truenas_disk_avgsz_(.+)_(?:reads|writes)\"\n      ),\n      \"op\", \"$1\", \"__name__\", \"scale_truenas_disk_avgsz_.+_(reads|writes)\"\n    )\n  )\n)\n/ 1024",
     "legendFormat": "{{disk }} - {{ op }}"
    }
   ]
  },
  {
   "title": "ARC Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\nscale_truenas_zfs_hits_rate_hits\n/\n(scale_truenas_zfs_hits_rate_hits + scale_truenas_zfs_hits_rate_misses)",
     "legendFormat": "L2"
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "smartmon_temperature_celsius_raw_value{smart_id=\"194\", type=\"sat\"}\n  * on(disk) group_left(serial_number, device_model)\n    smartmon_device_info{type=\"sat\", instance=\"10.100.0.20:9100\"}",
     "legendFormat": "{{ device_model }} - {{ disk }}"
    }
   ]
  }
 ]
}