---
- name: Export Wealthfolio daily adjusted totalValue and upload to Firefly Importer
  hosts: localhost
  gather_facts: false

  vars:
    # ==== ENV-driven config (Semaphore-friendly) ====
    wealthfolio_base_url: "{{ lookup('env', 'WEALTHFOLIO_BASE_URL') | default('', true) }}"
    wealthfolio_password: "{{ lookup('env', 'WEALTHFOLIO_PASSWORD') | default('', true) }}"
    wealthfolio_account_id: "{{ lookup('env', 'WEALTHFOLIO_ACCOUNT_ID') | default('TOTAL', true) }}"

    firefly_importer_base_url: "{{ lookup('env', 'FIREFLY_IMPORTER_BASE_URL') | default('', true) }}"
    firefly_importer_secret: "{{ lookup('env', 'FIREFLY_IMPORTER_SECRET') | default('', true) }}"
    firefly_access_token: "{{ lookup('env', 'FIREFLY_ACCESS_TOKEN') | default('', true) }}"

    output_dir: "{{ lookup('env', 'OUTPUT_DIR') | default('/tmp', true) }}"

    # ==== Output files ====
    out_csv: "{{ output_dir }}/wealthfolio_adjusted_pl_{{ wealthfolio_account_id }}.csv"
    out_json: "{{ output_dir }}/firefly_import_config.json"

    # ==== CSV constants ====
    csv_header: "DATE,ADJUSTED,OPPOSING ACCOUNT,Description"
    opposing_account_value: "Investment"
    description_value: "Investment Adjusted PL"

    # ==== Behavior toggles ====
    # If true: fail if API doesn't look newest->oldest
    enforce_api_order: "{{ (lookup('env', 'ENFORCE_API_ORDER') | default('false', true)) | bool }}"

  pre_tasks:
    - name: Validate required env vars
      ansible.builtin.assert:
        that:
          - wealthfolio_base_url | length > 0
          - wealthfolio_password | length > 0
          - firefly_importer_base_url | length > 0
          - firefly_importer_secret | length > 0
          - firefly_access_token | length > 0
        fail_msg: >
          Missing required env vars:
          WEALTHFOLIO_BASE_URL, WEALTHFOLIO_PASSWORD,
          FIREFLY_IMPORTER_BASE_URL, FIREFLY_IMPORTER_SECRET, FIREFLY_ACCESS_TOKEN

  tasks:
    - name: Login to Wealthfolio and get access token
      ansible.builtin.uri:
        url: "{{ wealthfolio_base_url }}/api/v1/auth/login"
        method: POST
        headers:
          Accept: "application/json"
          Content-Type: "application/json"
        body_format: json
        body:
          password: "{{ wealthfolio_password }}"
        return_content: true
        status_code: 200
      register: wf_login
      no_log: true

    - name: Extract token
      ansible.builtin.set_fact:
        wf_access_token: "{{ wf_login.json.accessToken }}"
        wf_token_type: "{{ wf_login.json.tokenType | default('Bearer') }}"

    - name: Fetch valuations history
      ansible.builtin.uri:
        url: "{{ wealthfolio_base_url }}/api/v1/valuations/history?accountId={{ wealthfolio_account_id }}"
        method: GET
        headers:
          Accept: "application/json"
          Authorization: "{{ wf_token_type }} {{ wf_access_token }}"
        return_content: true
        status_code: 200
      register: wf_vals
      no_log: true

    # ---- Normalize schema: list vs {data:[...]} ----
    - name: Normalize valuations list from API response
      ansible.builtin.set_fact:
        valuations_raw: >-
          {{
            (wf_vals.json.data if (wf_vals.json is mapping and 'data' in wf_vals.json) else wf_vals.json)
            | default([])
            | list
          }}

    - name: Filter only mapping entries (drop garbage rows)
      ansible.builtin.set_fact:
        valuations: "{{ valuations_raw | select('mapping') | list }}"

    - name: Report counts (non-sensitive)
      ansible.builtin.debug:
        msg:
          - "Valuations raw count: {{ valuations_raw | length }}"
          - "Valuations valid count: {{ valuations | length }}"
          - "Dropped entries: {{ (valuations_raw | length) - (valuations | length) }}"

    - name: Fail if no valuation entries
      ansible.builtin.assert:
        that:
          - valuations | length > 0
        fail_msg: "No valuation entries returned by Wealthfolio API."

    # ---- Optional order check (newest->oldest) ----
    - name: Detect likely order (newest->oldest) from first 2 items
      ansible.builtin.set_fact:
        api_newest_to_oldest: >-
          {{
            (valuations | length < 2)
            or
            ((valuations[0].valuationDate | default('')) >= (valuations[1].valuationDate | default('')))
          }}

    - name: Enforce API order if requested
      ansible.builtin.assert:
        that:
          - api_newest_to_oldest
        fail_msg: "API order not newest->oldest; delta computation would be wrong."
      when: enforce_api_order | bool

    # ---- Build CSV lines: Adjusted = totalValue[i] - totalValue[i+1] (newest->oldest) ----
    - name: Build CSV rows
      ansible.builtin.set_fact:
        csv_lines: "{{ (csv_lines | default([])) + [ line ] }}"
      vars:
        cur: "{{ valuations[item] }}"
        has_next: "{{ (item + 1) < (valuations | length) }}"
        cur_date: "{{ (cur.valuationDate | default(''))[:10] }}"
        adjusted_num: >-
          {{
            has_next
            | ternary(
                ((cur.totalValue | default(0)) | float) - ((valuations[item+1].totalValue | default(0)) | float),
                0.0
              )
          }}
        line: "{{ cur_date }},{{ '%.2f' | format(adjusted_num | float) }},{{ opposing_account_value }},{{ description_value }}"
      loop: "{{ range(0, valuations | length) | list }}"

    - name: Write CSV file
      ansible.builtin.copy:
        dest: "{{ out_csv }}"
        mode: "0600"
        content: |
          {{ csv_header }}
          {% for l in csv_lines %}
          {{ l }}
          {% endfor %}

    # ---- Firefly importer JSON config (static) ----
    - name: Write Firefly importer config JSON (static)
      ansible.builtin.copy:
        dest: "{{ out_json }}"
        mode: "0600"
        content: |
          {
              "version": 3,
              "source": "ff3-importer-1.7.8",
              "created_at": "2026-02-03T18:46:59+01:00",
              "date": "Y-m-d",
              "default_account": 25,
              "delimiter": "comma",
              "headers": true,
              "rules": false,
              "skip_form": false,
              "add_import_tag": false,
              "roles": [
                  "date_transaction",
                  "amount",
                  "opposing-name",
                  "description"
              ],
              "do_mapping": [
                  false,
                  false,
                  false,
                  false
              ],
              "mapping": [],
              "duplicate_detection_method": "classic",
              "ignore_duplicate_lines": true,
              "unique_column_index": 0,
              "unique_column_type": "internal_reference",
              "flow": "file",
              "content_type": "csv",
              "custom_tag": "",
              "identifier": "0",
              "connection": "0",
              "ignore_spectre_categories": false,
              "grouped_transaction_handling": "",
              "use_entire_opposing_address": false,
              "map_all_data": false,
              "pending_transactions": true,
              "access_token": "",
              "accounts": [],
              "new_account": [],
              "date_range": "",
              "date_range_number": 30,
              "date_range_unit": "d",
              "date_not_before": "",
              "date_not_after": "",
              "nordigen_country": "",
              "nordigen_bank": "",
              "nordigen_requisitions": [],
              "nordigen_max_days": "90",
              "conversion": false,
              "ignore_duplicate_transactions": false
          }

    # ---- Upload via curl: more reliable than uri multipart ----
    - name: Upload CSV+JSON to Firefly Importer (curl)
      ansible.builtin.command: >
        curl --silent --show-error --fail
        --location --request POST
        "{{ firefly_importer_base_url }}/autoupload?secret={{ firefly_importer_secret }}"
        --header "Accept: application/json"
        --header "Authorization: Bearer {{ firefly_access_token }}"
        --form "importable=@{{ out_csv }}"
        --form "json=@{{ out_json }}"
      register: ff_upload
      no_log: true

    - name: Show results (non-sensitive)
      ansible.builtin.debug:
        msg:
          - "CSV generated: {{ out_csv }}"
          - "JSON generated: {{ out_json }}"
          - "API newest->oldest detected: {{ api_newest_to_oldest }}"
          - "Firefly importer upload OK (curl exit 0)."
