{
 "title": "kiosk",
 "tags": [
  "OPNsense",
  "telegraf"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "dataSource", "label": "InfluxDB", "query": "influxdb" },
   { "name": "ESdataSource", "label": "ElasticSearch", "query": "elasticsearch" },
   {
    "name": "Host",
    "label": "OPNsense",
    "query": "from(bucket: v.defaultBucket)\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn:(r) => r._measurement == \"pf\")\r\n|> keyValues(keyColumns: [\"host\"])\r\n|> group()\r\n|> keep(columns: [\"host\"])\r\n|> distinct(column: \"host\")"
   },
   {
    "name": "Disk",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) => r._measurement == \"disk\" and\r\n  r.host =~ /^${Host:regex}$/)\r\n  |> keyValues(keyColumns: [\"device\"])\r\n  |> group()\r\n  |> keep(columns: [\"device\"])\r\n  |> distinct(column: \"device\")"
   },
   {
    "name": "Sensor",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn:(r) => r._measurement == \"temperature\" and\r\n    r.host =~ /^${Host:regex}$/)\r\n  |> keyValues(keyColumns: [\"sensor\"])\r\n  |> group()\r\n  |> keep(columns: [\"sensor\"])\r\n  |> distinct(column: \"sensor\")"
   },
   {
    "name": "LAN",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"interface\"\r\n  )\r\n  |> keyValues(keyColumns: [\"name\"])\r\n  |> group()\r\n  |> keep(columns: [\"name\"])\r\n  |> sort(columns: [\"name\"])\r\n"
   },
   {
    "name": "Gateway",
    "query": "from(bucket: v.defaultBucket)\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn:(r) => r._measurement == \"gateways\" and\r\n  r.host =~ /^${Host:regex}$/)\r\n|> keyValues(keyColumns: [\"gateway_name\"])\r\n|> group()\r\n|> keep(columns: [\"gateway_name\"])\r\n|> distinct(column: \"gateway_name\")"
   },
   { "name": "WAN", "query": "vtnet0" },
   {
    "name": "iface",
    "label": "FW_Interface",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"interface\")\r\n  |> last()\r\n  |> group(columns: [\"tag\"])\r\n  |> keep(columns: [\"name\"])"
   },
   {
    "name": "dst_port",
    "label": "FW_Destination Port",
    "query": "{\"find\": \"terms\", \"field\": \"dst_port\", \"query\": \"interface:$iface\", \"timestamp\": {\n\"timestamp\" : \"now-$__Interval_ms\"\n}}"
   },
   {
    "name": "src_ip",
    "label": "FW_Source IP",
    "query": "{\"find\": \"terms\", \"field\": \"src_ip\", \"query\": \"interface:$iface\", \"timestamp\": {\n\"timestamp\" : \"now-$__Interval_ms\"\n}}"
   },
   {
    "name": "dst_ip",
    "label": "FW_Destination IP",
    "query": "{\"find\": \"terms\", \"field\": \"dst_ip\", \"query\": \"interface:$iface\", \"timestamp\": {\n\"timestamp\" : \"now-$__Interval_ms\"\n}}"
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "pve-100 CPU ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"proxmox\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"cpustat\" and\n    r._field == \"cpu\"\n  )\n  |> filter(fn: (r) => r[\"host\"] == \"pve-100\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "temp pve-100",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  node_hwmon_temp_celsius{service=\"pve-100\"}[5m]\n)\n* on (chip, sensor, instance)\ngroup_right(label)\nnode_hwmon_sensor_label{label=~\"Tctl|Package id 0\", service=\"pve-100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: -20s)\r\n  |> filter(fn: (r) =>\r\n    r.host =~ /^${Host:regex}$/ and\r\n    r._measurement == \"cpu\" and\r\n    r._field == \"usage_idle\" and\r\n    r.cpu == \"cpu-total\"\r\n  )\r\n  |> map(fn: (r) => ({\r\n        r with\r\n        _value: r._value * -1.0 + 100.0\r\n      })\r\n    )\r\n  |> keep(columns: [\"_value\"])\r\n  |> last()"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"proxmox\")\r\n  |> range(start: -20s)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"system\" and\r\n    r._field == \"uptime\" and\r\n    r.host == \"pve-300\" and\r\n    r.object == \"nodes\"\r\n  )\r\n  |> keep(columns: [\"_value\"])\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: float(v: r._value) / 86400.0\r\n  }))"
    }
   ]
  },
  {
   "title": "epoch client-side",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "options": {
    "content": "<div\n  id=\"timeDisplay\"\n  style=\"\n    font-size:44px;\n    font-weight:600;\n    line-height:1;\n    overflow:hidden;\n    white-space:nowrap;\n    text-align:center;\n  \">\n</div>\n\n<script>\n  function updateTime() {\n    const now = new Date();\n    const h = String(now.getHours()).padStart(2, '0');\n    const m = String(now.getMinutes()).padStart(2, '0');\n    const s = String(now.getSeconds()).padStart(2, '0');\n    document.getElementById('timeDisplay').textContent = `${h}:${m}:${s}`;\n  }\n\n  updateTime();\n  setInterval(updateTime, 1000);\n</script>"
   }
  },
  {
   "title": "Firewall blocked events on WAN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:14",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:12", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "interface:$iface AND action:\"block\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "I/O Wait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"proxmox\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"cpustat\" and\n    r._field == \"wait\"\n  )\n  |> filter(fn: (r) => r[\"host\"] == \"pve-100\")\n  |> aggregateWindow(every: v.windowPeriod, fn:mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r.host =~ /^${Host:regex}$/ and\r\n    r._measurement == \"cpu\" and\r\n    r._field == \"usage_idle\")\r\n  |> map(fn: (r) => ({\r\n        r with\r\n        _value: r._value * -1.0 + 100.0\r\n      })\r\n    )\r\n  |> aggregateWindow(every: 10s, fn: last)\r\n  |> drop(columns: [\"host\"])"
    }
   ]
  },
  {
   "title": "Ram",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r.host =~ /^${Host:regex}$/ and\r\n    r._measurement == \"mem\" and\r\n    r._field == \"used_percent\"\r\n  )\r\n  |> aggregateWindow(every: 10s, fn: last)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:r._field}))\r\n  "
    }
   ]
  },
  {
   "title": "Most Blocked ip",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:120",
       "fake": true,
       "field": "src-ip",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "1" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:118", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "action:\"block\" AND interface:vtnet0 AND NOT src-ip:93.49.80.101 AND NOT src-ip:172.24.1.*",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "pve-300 CPU ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"proxmox\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"cpustat\" and\n    r._field == \"cpu\"\n  )\n  |> filter(fn: (r) => r[\"host\"] == \"pve-300\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "temp pve-300",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  node_hwmon_temp_celsius{service=\"pve-300\"}[5m]\n)\n* on (chip, sensor, instance)\ngroup_right(label)\nnode_hwmon_sensor_label{label=~\"Tctl|Package id 0\", service=\"pve-300\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Firewall Blocked Destination Ports on $iface",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1775",
       "fake": true,
       "field": "dst-port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1776",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1773", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "interface:$iface AND src-ip:$src_ip AND dst-port:$dst_port AND action:\"block\" AND source:$Host",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Firewall Blocked Event Locations on vtnet0",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 12, "x": 6, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "src-ip-geo-country",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "interface:$iface AND NOT src-ip:93.49.80.101 AND NOT src-ip:172.24.1.58 AND src-ip:$src_ip AND action:\"block\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "I/O Wait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"proxmox\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"cpustat\" and\n    r._field == \"wait\"\n  )\n  |> filter(fn: (r) => r[\"host\"] == \"pve-300\")\n  |> aggregateWindow(every: v.windowPeriod, fn:mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Active Power (W)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hass_power_watts{entity=\"sensor.battery_charger_power\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Line Voltage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hass_voltage_volts{entity=\"sensor.battery_charger_voltage\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Pools",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"proxmox\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"system\")\n  |> filter(fn: (r) => r._field == \"avail\" or r._field == \"used\")\n  |> filter(fn: (r) => r[\"nodename\"] == \"pve-100\")\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with \n    _time: r._time,\n    _measurement: r.measurement,\n    _field: \"used_perc\",\n    _value: float(v: 100) / (float(v: r.avail) + float(v: r.used)) * float(v:r.used)\n     }))\n  |> drop(columns: [\"avail\",\"used\"])\n"
    },
    {
     "query": "from(bucket: \"proxmox\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"system\")\n  |> filter(fn: (r) => r._field == \"avail\" or r._field == \"used\")\n  |> filter(fn: (r) => r[\"nodename\"] == \"pve-300\")\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with \n    _time: r._time,\n    _measurement: r.measurement,\n    _field: \"used_perc\",\n    _value: float(v: 100) / (float(v: r.avail) + float(v: r.used)) * float(v:r.used)\n     }))\n  |> drop(columns: [\"avail\",\"used\"])\n"
    }
   ]
  },
  {
   "title": "Power Factor (cos φ) ±5% tolerance",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(hass_power_watts{entity=\"sensor.battery_charger_power\"})\n/\n(\n  scalar(hass_voltage_volts{entity=\"sensor.battery_charger_voltage\"})\n  *\n  scalar(hass_current_amperes{entity=\"sensor.battery_charger_current\"})\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apparent Power (VA)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  scalar(hass_voltage_volts{entity=\"sensor.battery_charger_voltage\"})\n  *\n  scalar(hass_current_amperes{entity=\"sensor.battery_charger_current\"})\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "expr": "hass_voltage_volts{entity=\"sensor.battery_charger_voltage\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway RTT - $Gateway ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r.host =~ /^${Host:regex}$/ and\r\n    r.gateway_name =~ /^${Gateway:regex}$/ and\r\n    r._measurement == \"gateways\" and\r\n    r._field == \"delay\"\r\n  )"
    }
   ]
  },
  {
   "title": "Packet lost 0%",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r.host =~ /^${Host:regex}$/ and\r\n    r.gateway_name =~ /^${Gateway:regex}$/ and\r\n    r._measurement == \"gateways\" and\r\n    r._field == \"loss\"\r\n  )"
    }
   ]
  },
  {
   "title": "WAN Traffic - Bits/sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r.host =~ /^${Host:regex}$/ and\r\n    r.interface =~ /^${WAN:regex}$/ and \r\n    r._measurement == \"net\" and\r\n    r._field =~ /bytes_recv|bytes_sent/\r\n  )\r\n  |> aggregateWindow(every: 10s, fn: last)\r\n  |> derivative(unit:1s)\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: r._value * 8.0\r\n    })\r\n  )\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:r._field}))"
    }
   ]
  },
  {
   "title": "Docker cntiner cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(container_cpu_usage_seconds_total{image!=\"\", name!=\"\" , name!~\"^[0-9a-f]{12,}$\"}[10m])\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "K8s pod cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (container_name, pod_name)",
     "legendFormat": "{{ image }}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "{{ image }}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (kubernetes_io_hostname, rkt_container_name)",
     "legendFormat": "{{ image }}"
    }
   ]
  }
 ]
}