- name: stop a system service
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  vars:
    service_name: "sshd" 

  tasks:
    - name: "Stop the {{ service_name }} service"
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: stopped
