- name: Update time and timezone on VMs and LXC containers
  hosts: all
  become: yes
  vars:
    # Set the desired timezone, e.g., "Europe/Rome"
    new_timezone: "Europe/Rome"

  tasks:
    - name: Update the timezone using tzdata
      ansible.builtin.timezone:
        name: "{{ new_timezone }}"
