- name: Update time and timezone on VMs and LXC containers
  hosts: all
  become: yes
  vars:
    # Set the desired timezone, e.g., "Europe/Rome"
    new_timezone: "Europe/Rome"
    # Set the NTP server to use for time synchronization
    ntp_server: "pool.ntp.org"

  tasks:
    - name: Set the timezone using tzdata
      ansible.builtin.timezone:
        name: "{{ new_timezone }}"
      # This task sets the system timezone using the tzdata module.

    - name: Ensure ntpdate is installed (Debian/Ubuntu only)
      ansible.builtin.apt:
        name: ntpdate
        state: present
      when: ansible_os_family == "Debian"
      # This task installs the ntpdate package if it is not already present.

    - name: Force update system time using ntpdate
      ansible.builtin.command: ntpdate -b -u {{ ntp_server }}
      register: ntp_update
      changed_when: true
      # This task forces the system clock to synchronize with the specified NTP server.
      # The '-b' option forces a step adjustment (required when the time difference is large),
      # while '-u' specifies the use of an unprivileged port.

    - name: Update the hardware clock (RTC) with the system time
      ansible.builtin.command: hwclock --systohc
      # This task writes the current system time to the hardware clock (RTC), ensuring both clocks are in sync.
