---
- name: Obtain/Renew SSL Certificate for a Domain Using Cloudflare DNS
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  vars:
    domain_name: "domain.com"           # ❗ Replace with your domain
    email: "admin@domain.com"           # ❗ Replace with your email
    cloudflare_token: "abcdefg1234567"  # ❗ Replace with your actual token
    cf_credentials_path: "/etc/letsencrypt/secrets/cloudflare-{{ domain_name }}.ini"

  tasks:
    - name: Install Certbot and DNS-Cloudflare plugin
      apt:
        name:
          - certbot
          - python3-certbot-dns-cloudflare
        state: present
        update_cache: yes

    - name: Create directory for Cloudflare credentials
      file:
        path: "/etc/letsencrypt/secrets"
        state: directory
        owner: root
        group: root
        mode: "0700"

    - name: Write Cloudflare credentials file for {{ domain_name }}
      copy:
        dest: "{{ cf_credentials_path }}"
        content: |
          dns_cloudflare_api_token = {{ cloudflare_token }}
        owner: root
        group: root
        mode: "0600"

    - name: Check existence of certificate for {{ domain_name }}
      stat:
        path: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
      register: cert_stat

    - name: Initial issuance of SSL certificate for {{ domain_name }}
      command: >
        certbot certonly
        --dns-cloudflare
        --dns-cloudflare-credentials "{{ cf_credentials_path }}"
        -d "{{ domain_name }}"
        --agree-tos
        --non-interactive
        --email "{{ email }}"
      args:
        creates: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
      when: not cert_stat.stat.exists
      register: certbot_initial

    - name: Force renewal of certificate (if requested)
      command: >
        certbot certonly
        --dns-cloudflare
        --dns-cloudflare-credentials "{{ cf_credentials_path }}"
        -d "{{ domain_name }}"
        --agree-tos
        --non-interactive
        --email "{{ email }}"
        --force-renewal
      when:
        - cert_stat.stat.exists
        - force_renew | default(false)
      register: certbot_forcerenew

    - name: Debug: issuance/renewal result
      debug:
        msg: |
          {% if certbot_initial is defined and (certbot_initial.rc | default(1)) == 0 %}
          ✅ Initial certificate for {{ domain_name }} created successfully.
          You can find it in /etc/letsencrypt/live/{{ domain_name }}/
          {% elif certbot_forcerenew is defined and (certbot_forcerenew.rc | default(1)) == 0 %}
          🔄 Certificate for {{ domain_name }} was renewed (forced) successfully.
          You can find it in /etc/letsencrypt/live/{{ domain_name }}/
          {% else %}
          ℹ️ Certificate for {{ domain_name }} already exists and was not force renewed.
          Check /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem
          {% endif %}
